ElectronsTriggerBarrel:
  sample: DYLL_M50
  versions: V30
  objects:
    EG: 
      suffix: "Pt"
      label: "EG"
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.8"
    tkElectron:
      suffix: "Pt"
      label: "tkElectron"
      cuts:
        - "{passeseleid} == 1"
        - "abs({eta}) < 2.8"
  binning:  # is passed to np.logspace 
    min: 0
    max: 100
    step: 10

ElectronsTriggerBarrelV29vsV30:
  sample: DYLL_M50
  versions:
    - V29
    - V30
  objects:
    EG: 
      suffix: "Pt"
      label: "EG"
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.8"
  binning:  # is passed to np.logspace 
    min: 0 
    max: 100
    step: 10
